spring:
  datasource:
    url: jdbc:postgresql://ep-frosty-feather-aosfqpja-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_yUG3Qo0cmSgZ
  jpa:
    hibernate:
      ddl-auto: validate   # NEVER 'update' — Flyway owns schema, not Hibernate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
